swagger: "2.0"
info:
  description: "service for registering foosball teams for the upcoming season.
  \nFLow:
  \n  * User logs in
  \n  * First site is a list of teams, the user is in charge for
  \n  * On the team site the user can see the current lineup and create a lineup for the upcoming season
  \n  * On a player-profile site, the user can see all the necessary player-credentials
  \n"
  version: "0.0.1"
  title: "league-registration"
host: yi.pi.yi.pi.yeah
basePath: /league-registration
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
definitions:
  # A simple username/password combo for logging in
  login:
    required: [username, password]
    properties:
      username:
        type: string
        minLength: 1
      password:
        type: string
        minLength: 1
  player:
    properties:
      id:
        type: string
      nationalPlayerNr:
        type: string
      internationalPlayerNr:
        type: string
      lastname:
        type: string
      firstname:
        type: string
      club:
        type: string
      gender:
        type: string
      birthdate:
        type: string
      emailAddress:
        type: string
      phone:
        type: number
  team:
    properties:
      id:
        type: string
      name:
        type: string
      club:
        $ref: '#/definitions/club'
      homeWeekday:
        type: number
      hometable:
        $ref: '#/definitions/tableType'
      homeLocation:
        $ref: '#/definitions/location'
      lineupList:
        type: array
        items:
          $ref: '#/definitions/lineup'
  club:
    properties:
      id:
        type: string
      name:
        type: string
  location:
    properties:
      id:
        type: string
      name:
        type: string
      street:
        type: string
      city:
        type: string
      zip:
        type: string
  tableType:
    properties:
      id:
        type: string
      name:
        type: string
  lineup:
    properties:
      id:
        type: string
      team:
        $ref: '#/definitions/team'
      season:
        $ref: '#/definitions/season'
      players:
        type: array
        items:
          $ref: '#/definitions/player'
  season:
    properties:
      id:
        type: string
      name:
        type: string

# NOTE: This does NOT set global parameters for all operations.
# It just defines parameter templates that can be referenced by operations (i.e. it saves typing)
parameters:
  sessionCookie: &sessionCookie
    name: Cookie
    in: header
    required: true
    type: string
    description: The session cookie

  # username: &username
   # name: username
    # in: path
    # required: true
    # type: string
    # description: This is the {username} path parameter
  offsetParam:
    in: query
    name: offset
    required: false
    type: integer
    minimum: 0
    description: The number of items to skip before starting to collect the result set.
  limitParam:
    in: query
    name: limit
    required: false
    type: integer
    minimum: 1
    maximum: 50
    default: 20
    description: The numbers of items to return.
paths:
  /login:
    post:
      summary: Logs in
      description: |
        Try logging in with username "jdoe" and password "jdoe".
        Then try logging in with username "admin" and password "admin".
      parameters:
        - name: body
          in: body
          required: true
          description: The login credentials
          schema:
            $ref: '#/definitions/login'
      responses:
        200:
          description: Login was successful
          headers:
            Set-Cookie:
              type: string
              description: The session cookie
              default: demo-session-id=123456789012345678901234567890

  /logout:
    post:
      summary: Logs out the given user
      description: >
        Users can only log themselves out, not other users. Except the "admin" user, who can log-out anyone.
      parameters:
        - *sessionCookie
      responses:
        204:
          description: Logout was successful
          headers:
            Set-Cookie:
              type: string
              description: Deletes the session cookie (by making expire in the past)
              default: demo-session-id=deleted; Expires=Thu, 01-Jan-1970 00:00:01 GMT; Path=/
        401:
          description: You tried to log someone else out, and you're not the "admin" user.
        404:
          description: The {username} was not found
  /team:
    get:
      summary: gets the teams the user is responsible for
      description: todo
      responses:
        200:
          description: OK
    post:
      responses:
        200:
          description: OK
    patch:
      responses:
        200:
          description: OK
    delete:
      responses:
        200:
          description: OK
  /team/{teamId}:
    get:
      summary: gets a team with all informations and related players for the current and the upcoming season
      description: todo
      parameters:
        - name: teamId
          in: path
          description: String input for echo service
          required: true
          type: string
      responses:
        200:
          description: OK
    post:
      summary: post the lineup for the upcoming season
      description: todo
      responses:
        200:
          description: OK
    patch:
      summary: patches the lineup for the upcoming season with new information
      responses:
        200:
          description: OK
    delete:
      summary: deletes the lineup for the upcoming season
      responses:
        200:
          description: OK
  /lineup/{lineupId}:
    get:
      summary: gets a lineup
      description: todo
      parameters:
        - name: lineupId
          in: path
          description: String input for echo service
          required: true
          type: string
      responses:
        200:
          description: OK
    post:
      summary: post the lineup for the upcoming season
      description: todo
      responses:
        200:
          description: OK
    patch:
      summary: patches the lineup for the upcoming season with new information
      responses:
        200:
          description: OK
    delete:
      summary: deletes the lineup for the upcoming season
      responses:
        200:
          description: OK
  /player:
    get:
      description: todo
      responses:
        200:
          description: OK
    post:
      responses:
        200:
          description: OK
    patch:
      responses:
        200:
          description: OK
    delete:
      responses:
        200:
          description: OK
  /player/search:
    get:
      summary: searches for players to add to a lineup
      parameters:
        - name: forename
          type: string
          in: query
          minLength: 1
          required: true
        - name: surname
          type: string
          in: query
          minLength: 1
          required: true
        - $ref: '#/parameters/offsetParam'
        - $ref: '#/parameters/limitParam'
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/player'
  /club:
    get:
      responses:
        200:
          description: OK
    post:
      responses:
        200:
          description: OK
    patch:
      responses:
        200:
          description: OK
    delete:
      responses:
        200:
          description: OK
  /location:
    get:
      responses:
        200:
          description: OK
    post:
      responses:
        200:
          description: OK
    patch:
      responses:
        200:
          description: OK
    delete:
      responses:
        200:
          description: OK
  